sudo: false
language: ruby
services:
  - postgresql
notifications:
  email:
    - bruno@atnos.com
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create
  - bundle exec rake db:migrate
